// docs-site/sidebars.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  tutorialSidebar: [
    // Introduction Section
    {
      type: 'doc',
      id: 'intro',
      label: 'Welcome to MS Code'
    },
    
    // Core Concepts
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      className: 'category-getting-started',
      items: [
        'getting-started/what-is-an-extension',
        'getting-started/ready-an-extension',
        'getting-started/extension-structure',
        'getting-started/know-manifest-json',
        'getting-started/understanding-main',
        'getting-started/know-setting-configurations',
        'getting-started/core-modules-api',
        'getting-started/advanced-react-ui',
        'getting-started/code-professional-extension',
        'getting-started/compile-and-build'
      ],
    },

    // Guides
    {
      type: 'category',
      label: 'Advanced Guides',
      collapsible: true,
      collapsed: false,
      className: 'category-advanced-guides',
      items: [{
        type : 'autogenerated',
        dirName: 'guides'
      }],
    },

    // API Reference
    {
      type: 'category',
      label: 'Extension API Ref',
      collapsible: true,
      collapsed: true,
      className: 'category-api-ref',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api'
        },
      ],
    },
  ],
};